version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - /var/lib/mysql
  postgresql:
    image: postgres:15.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
    volumes:
      - /var/lib/postgresql/data
  node-app:
    build: ./gate-simulator
    ports:
      - '9999:9999'