version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=pass888
      - MYSQL_USER=lama888
      - MYSQL_DATABASE=mysql

  postgresql:
    image: postgres:14.0
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/db
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=postgres
      - POSTGRES_USER=lama888
      - POSTGRES_PASSWORD=pass888